name: Doxygen for GitHub Pages

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Doxygen
      uses: DenverCoder1/doxygen-github-pages-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: docs/html
